apiVersion: v1
kind: Pod
metadata:
  name: test-pd-emptydir
spec:
  containers:
  - image: scmgalaxy/nginx-devopsschoolv1
    name: test-container
    volumeMounts:
    - mountPath: /asif
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
