apiVersion: v1
kind: PersistentVolume
metadata:
  name: asif-pv-2
spec:
  capacity:
    storage: 3Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tecnotree
    server: 172.31.18.137
  persistentVolumeReclaimPolicy: Recycle

