apiVersion: v1
kind: PersistentVolume
metadata:
  name: sauravpvcheck23
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tecnotree/saurav/pv0003
    server: 172.31.18.137 
  persistentVolumeReclaimPolicy: Recycle
