apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-mg
spec:
  replicas: 1   
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-mukund
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
