apiVersion: v1
kind: ReplicationController
metadata:
  name: http-rc-new
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mahim-service-nodeport
    spec:
      containers:
      - name: hello-onmo
        image: scmgalaxy/nginx-devopsschoolv2
        ports:
        - containerPort: 80
