apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - image: scmgalaxy/nginx-devopsschoolv1
    name: hostpath
    volumeMounts:
    - mountPath: /vol
      name: hostpath-vol
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /data
      type: DirectoryOrCreate
