apiVersion: v1
kind: Pod
metadata:
  name: agasthi-pod-multi
  labels: 
    app: multi-nginx
spec:
  containers:
  - name: nginx-ctr-80
    image: nginx
    ports:
    - containerPort: 80
  - name: httpd-ctr-8080
    image: httpd
    ports:
    - containerPort: 8080

