apiVersion: v1
kind: ReplicationController
metadata:
  name: agasthi-rc
spec:
  replicas: 3  
  template:
    metadata:
      labels:
        app: agasthi-world
    spec:
      containers:
      - name: hello-ctr
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
