kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tecnotree-admin-madhutest
subjects:
- kind: ServiceAccount
  name: tecnotree-admin-madhutest
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tecnotree-admin-madhutest
  apiGroup: rbac.authorization.k8s.io
