apiVersion: v1
kind: Pod
metadata:
  name: configmap
  labels:
    app: helloworld-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-volume
      configMap:
        name: test-config
        items:
        - key: test.conf
          path: myconf.conf
