kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shantha-cr-binding
subjects:
- kind: ServiceAccount
  name: shantha-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: shantha-clusterroles2
  apiGroup: rbac.authorization.k8s.io
