apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-np
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    environment: training
  sessionAffinity: None
  type: NodePort
