apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-sergio
spec:
  replicas: 2
  selector:
    app: nginx-sergio
  template:
    metadata:
      name: nginx-sergio
      labels:
        app: nginx-sergio
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
