apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  selfLink: /api/v1/namespaces/sergio/services/nginx
spec:
  ports:
  - name: 5555-80
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    env: training
    location: aws
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
