apiVersion: apps/v1
kind: Deployment
metadata:
  name: priya-apache
spec:
  selector:
    matchLabels:
      run: priya-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: priya-apache
    spec:
      containers:
      - name: priya-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
