apiVersion: v1
kind: Pod
metadata:
  name: priya-vol-host
spec:
  containers:
  - image: scmgalaxy/nginx-devopsschoolv1
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-vol-priya
  volumes:
  - name: test-vol-priya
    hostPath:
      path: /data
      type: DirectoryOrCreate
