apiVersion: v1
kind: PersistentVolume
metadata:
  name: sspv1
spec:
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tecnotree/sspv
    server: 172.31.18.137 
  persistentVolumeReclaimPolicy: Recycle
