apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv00010 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tecnotree
    server: 172.31.18.137
  persistentVolumeReclaimPolicy: Recycle
