apiVersion: v1
kind: Pod
metadata:
  name: helloworld-nginx-raj1
  labels:
    app: helloworld-nginx-raj1
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - containerPort: 3000
  volumes:
    - name: config-volume
      configMap:
        name: my-config-mohan
        items:
        - key: reverseproxy.conf
          path: myconfo.conf
