kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dep-manager-binding
  namespace: mohammed
subjects:
- kind: User
  name: asif
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
